- name: Run simpleapi
  docker_container:
    name: simpleapi
    image: planche69/devops-backend:latest
    env:
      DB_URL: "jdbc:postgresql://database:5432/db"
      DB_USR: "usr"
      DB_PWD: "pwd"
    networks:
      - name: "app-network"