- name: Run simpleapi
  docker_container:
    name: simpleapi
    image: planche69/devops-backend:latest
    env:
      DB_URL: "{{ db_url }}"
      DB_USR: "{{ db_usr }}"
      DB_PWD: "{{ db_pwd }}"
    networks:
      - name: "app-network"