name: deploy_ansible

on:
    workflow_run:
        workflows: [publish_image]
        types:
            - completed
        branches:
            - main

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            - name: Run playbook
              uses: dawidd6/action-ansible-playbook@v2
              with:
                  # Required, playbook filepath
                  playbook: ansible/playbook/main.yml
                  # Optional, SSH private key
                  key: ${{secrets.SSH_PRIVATE_KEY}}
                  # Optional, literal inventory file contents
                  inventory: |
                      [all]
                      ${{secrets.SERVER_ADDRESS}}
                  # Optional, encrypted vault password
                  vault_password: ${{secrets.VAULT_PASSWORD}}
                  options: |
                      -u ${{secrets.SSH_USER}}
                      --verbose